# 10-cortex.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
  namespace: soc-platform
data:
  application.conf: |
    # Cortex configuration
    search {
      uri = "http://elasticsearch:9200"
    }
    
    storage {
      config {
        # Use local storage for jobs
        job-directory = "/tmp/cortex-jobs"
        docker-job-directory = "/tmp/cortex-jobs"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: soc-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
      - name: cortex
        image: thehiveproject/cortex:3.1.3-1
        ports:
        - containerPort: 9001
        env:
        - name: JOB_DIRECTORY
          value: "/tmp/cortex-jobs"
        - name: DOCKER_JOB_DIRECTORY
          value: "/tmp/cortex-jobs"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: cortex-config
          mountPath: /etc/cortex/application.conf
          subPath: application.conf
        - name: job-storage
          mountPath: /tmp/cortex-jobs
        livenessProbe:
          httpGet:
            path: /api/status
            port: 9001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/status
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: job-storage
          mountPath: /tmp/cortex-jobs
      volumes:
      - name: cortex-config
        configMap:
          name: cortex-config
      - name: job-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cortex
  namespace: soc-platform
spec:
  type: NodePort
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30091
  selector:
    app: cortex